/*
  # Initial Data Setup

  1. Changes
    - Insert all income codes
    - Insert all establishments

  2. Security
    - Uses ON CONFLICT to safely handle duplicates
*/

-- Insert the income codes
INSERT INTO income_codes (code, description)
SELECT code, description
FROM (
  VALUES
    ('20000', 'SERVICIOS NO PERSONALES'),
    ('21000', 'SERVICIOS BASICOS'),
    ('21420', 'TELEFONIA FIJA'),
    ('21430', 'TELEFONIA CELULAR'),
    ('23000', 'MANTENIMIENTO REPARACIONES Y LIMPIEZA'),
    ('23100', 'MANTENIMIENTO Y REPARACION DE EDIFICIOS Y LOCALES'),
    ('23200', 'MANTENIMIENTO Y REPARACION DE EQUIPOS Y MEDIO DE TRANSPORTE'),
    ('23300', 'MANTENIMIENTO Y REPARACION DE EQUIPOS SANITARIOS Y LABORATORIO'),
    ('23360', 'MANTENIMIENTO Y REPARACION DE OFICINA Y MUEBLES'),
    ('23390', 'MANTENIMIENTO Y REPARACION DE OTROS EQUIPOS'),
    ('23400', 'MANTENIMIENTO Y REPARACION DE OBRAS E INSTALACIONES VARIAS'),
    ('23500', 'LIMPIEZA, ASEO Y FUMIGACION'),
    ('23600', 'MANTENIMIENTO DE SISTEMANS INFORMATICOS'),
    ('24000', 'SERVICIOS PROFESIONALES'),
    ('24130', 'SERVICIOS MEDICOS'),
    ('24500', 'SERVICIO DE CAPACITACION'),
    ('24900', 'OTROS SERVICIOS TECNICOS PROFESIONALES'),
    ('25000', 'SEVICIOS COMERCIALES Y FINANCIEROS'),
    ('25100', 'SERVICIO DE TRANSPORTE'),
    ('25300', 'SERVICIO DE IMPRENTA, PUBLICACIONES Y REPRODUCCIONES'),
    ('25500', 'COMICIONES Y GASTOS BANCARIOS'),
    ('25600', 'PUBLICIDAD Y PROPAGANDA'),
    ('25700', 'SERVICIO DE INTERNET'),
    ('25900', 'VIAJES'),
    ('26000', 'PUBLICIDAD Y PROPAGANDA'),
    ('26100', 'PASAJES NACIONALES'),
    ('26210', 'VIATICOS'),
    ('29000', 'OTROS SERVICIOS NO PERSONALES'),
    ('29200', 'SERVICIO DE VIGILANCIA'),
    ('31000', 'ALIMENTOS, PRODUCTOS AGROPECUARIOS Y FORESTALES'),
    ('31100', 'ALIMENTOS Y BEBIDAS PARA PERSONAS'),
    ('31500', 'MADERA, CORCHO Y SUS MANUFACTURAS'),
    ('32100', 'HILADOS Y TELAS'),
    ('32200', 'CONFECCIONES TEXTILES'),
    ('32300', 'PRENDAS DE VESTIR'),
    ('33000', 'PRODUCTOS DE DE PAPEL Y CARTON'),
    ('33100', 'PAPEL DE ESCRITORIO'),
    ('33200', 'PAPEL PARA COMPUTACION'),
    ('33300', 'PRODUCTOS DE ARTES GRAFICAS'),
    ('33400', 'PRODUCTOS DE PAPEL Y CARTON'),
    ('34100', 'CUEROS Y OPIELES'),
    ('34300', 'ARTICULOS DE CAUCHO'),
    ('34400', 'LLANTAS Y CAMARAS DE AIRE'),
    ('35100', 'PRODUCTOS QUIMICOS'),
    ('35200', 'PRODUCTOS FARMACEUTICOS Y MEDICINALES'),
    ('35210', 'PRODUCTOS FARMACEUTICOS Y MEDICINALES VARIOS'),
    ('35260', 'OXIGENO'),
    ('35265', 'REACTIVOS'),
    ('35266', 'OXIGENO MEDICO'),
    ('35270', 'VENDAJES PARA FRACTURAS'),
    ('35400', 'INSECTICIDAS FUGICIDAS Y OTROS'),
    ('35500', 'TINTAS PINTURAS Y COLORANTES'),
    ('35600', 'COMBUSTIBLE Y LUBRICANTES'),
    ('35610', 'GASOLINA'),
    ('35620', 'DIESEL'),
    ('35630', 'KEROSEN'),
    ('35640', 'GAS LPG'),
    ('35650', 'ACEITES Y GRASAS LUBRICANTES'),
    ('35800', 'PRODUCTOS DE MATERIAL PLASTICO'),
    ('35900', 'OTROS PRODUCTOS QUIMICOS'),
    ('36100', 'PRODUCTOS FERROSOS'),
    ('36300', 'ESTRUCTURAS METALICAS ACABADAS'),
    ('36400', 'HERRAMIENTAS MENORES'),
    ('36900', 'OTROS PRODUCTOS METALICOS'),
    ('36920', 'ACCESORIOS DE METAL'),
    ('36930', 'ELEMENTOS DE FERRETERIA'),
    ('37200', 'PRODUCTOS DE VIDRIO'),
    ('37300', 'PRODUCTOS DE LOZA Y PORCELANA'),
    ('37400', 'PRODUCTOS DE CEMENTO ASBESTO Y YESO'),
    ('37500', 'CEMENTO CAL Y YESO'),
    ('38400', 'PIEDRA, ARCILLA Y ARENA'),
    ('39100', 'ELEMENTOS DE LIMPIEZA'),
    ('39200', 'UTILES DE ESCRITORIO OFICINA Y ENCEÑANZA'),
    ('39300', 'UTILES MATERIALES ELECTRICOS'),
    ('39400', 'UTENSILIOS DE COCINA Y COMEDOR'),
    ('39500', 'INSTRUMENTAL MEDICO QUIRURGICO MENOR Y DE LABORATORIO'),
    ('39510', 'INSTRUMENTAL MEDICO QUIRURGICO MENOR'),
    ('39520', 'INSTRUMENTAL Y MATERIAL PARA LABORATORIO'),
    ('39530', 'MATERIAL MEDICO QUIRURGICO MENOR'),
    ('39540', 'OTROS INSTRUMENTAL ACCESORIOS Y MATERIAL MEDICO'),
    ('39550', 'INSTRUMENTAL ODONTOLOGICO'),
    ('39560', 'MATERIALES Y SUMINISTROS ODONTOLOGICOS'),
    ('39900', 'OTROS GASTO Y ACCESORIOS'),
    ('41240', 'INSTALACIONES VARIAS'),
    ('42100', 'EQUIPO DE MEDICINA Y MUEBLES'),
    ('42110', 'MUEBLES VARIOS DE OFICINA'),
    ('42120', 'EQUIPOS VARIOS DE OFICINA'),
    ('42140', 'ELECTRODOMESTICOS'),
    ('42200', 'MAQUINARIA Y EQUIPO DE PRODUCCION'),
    ('42210', 'EQUIPO MEDICO SANITARIO Y HOSPITALARIO E INSTRUMENTAL'),
    ('42420', 'EQUIPO DE LABORATORIO'),
    ('42500', 'EQUIPO DE COMUNICACION Y SEÑALAMIETO'),
    ('42600', 'EQUIPO PARA COMPUTACION'),
    ('47210', 'CONSTRUCCIONES Y MEJORAS')
  ) AS t(code, description)
ON CONFLICT (code) DO NOTHING;

-- Insert the establishments
INSERT INTO establishments (name)
SELECT name
FROM (
  VALUES
    ('Choloma'),
    ('Monterrey'),
    ('Lopez Arellano'),
    ('El Rancho'),
    ('La Jutosa'),
    ('Quebrada Seca'),
    ('IHSS Choloma'),
    ('La Bueso'),
    ('SMI Choloma'),
    ('Yami Rosental Hidalgo'),
    ('Omoa'),
    ('Cuyamelito'),
    ('Paraiso'),
    ('Jalisco'),
    ('Tegucigalpita'),
    ('Chachauala'),
    ('Julio Cesar Santos (Corintio)'),
    ('Sra. Sinia Lujan (Tulian Rios)'),
    ('Cuyamel'),
    ('Santa Teresa'),
    ('Coleo Alvarez Casildo'),
    ('German Pascua Piemienta'),
    ('Santiago'),
    ('Dr. Raul Alfredo Ugarte'),
    ('Suyapa'),
    ('Jordan'),
    ('Potrerillos'),
    ('Comello Moncada'),
    ('Bajamar'),
    ('Baracoa'),
    ('Caoba'),
    ('Kele kele'),
    ('La Pita'),
    ('Puente Alto'),
    ('Calan PT'),
    ('Saraguayna'),
    ('Travesia'),
    ('La Fraternidad'),
    ('Sra. Linda Coello (Medina)'),
    ('San Antonio (S. Barahona)'),
    ('Nueva Granada'),
    ('San Juan'),
    ('La Ceibita'),
    ('Sotero Barahona'),
    ('Rio Lindo'),
    ('San Francisco de Y.'),
    ('Teodoro Mancia'),
    ('Tacamiche'),
    ('La Sabana'),
    ('San Manuel'),
    ('Cowlee'),
    ('Guadalupe'),
    ('El Plan'),
    ('EL LLAMO (Amor Sanchez)'),
    ('Peña Blanca'),
    ('Las Flores'),
    ('Sta Cruz (Francisco Beltran)'),
    ('Yojoa'),
    ('San Isidro'),
    ('Los Caminos'),
    ('SMI Juan Pablo II'),
    ('Ing. Roberto Pineda Chacon (La Bolsita)'),
    ('Los Cutucos'),
    ('Jose Ines Rapalo (Villanueva)'),
    ('Dos Caminos'),
    ('El Milagro'),
    ('El Venado'),
    ('Nuevo Chameleon'),
    ('San Isidro II'),
    ('El Calan'),
    ('Sauce'),
    ('Nueva Suyapa'),
    ('SMI Villanueva'),
    ('Pueblo Nuevo'),
    ('Dr. Walter Perdomo (Col. Gracias a Dios)'),
    ('El Marañon'),
    ('El Perico'),
    ('Sinal'),
    ('Colinas de Suiza'),
    ('Nuestra Señora de Guadalupe'),
    ('La Lima'),
    ('Planeta'),
    ('Flores de Oriente')
  ) AS t(name)
ON CONFLICT (name) DO NOTHING;